spring:
  application:
    name:yeb
  datasource:
    url: jdbc:mysql://8.142.13.119:3306/yeb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    hikari:
      max-lifetime: 500000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zqz.1234
  redis:
    timeout: 10000ms
    host: 8.142.13.119
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
    password: root
server:
  port: 8888
jwt :
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearer
